INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Andres','Guzman','profesor@bolsasdeideas.com','2018-01-01');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Mr. John','Doe','jonh.doe@gmail.com','2018-01-02');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Linus','Torvalds','linus.torvalds@gmail.com','2018-01-03');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Rasmus','Lerdorf','rasmus.lerdorf@gmail.com','2018-01-04');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Erich','Gamma','erich.gamma@gmail.com','2018-02-01');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Richard','Helm','richard.helm@gmail.com','2018-02-10');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Ralph','Johnson','ralph.johnson@gmail.com','2018-02-18');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('John','Vilissides','john.vilissidesr@gmail.com','2018-02-29');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Dr. James','Gosling','james.goslin@gmail.com','2018-03-03');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Magma','Lee','magma.lee@gmail.com','2018-03-04');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Tornado','Roe','tornado.roe@gmail.com','2018-03-05');
INSERT INTO cliente(nombre, apellido, email, create_at) VALUES('Jade','Doe','jade.doe@gmail.com','2018-03-06');