CREATE TABLE solicitud_cabe (
  create_at date DEFAULT NULL,
  grantotal float DEFAULT NULL,
  impuesto float DEFAULT NULL,
  total float DEFAULT NULL,
  id bigint NOT NULL AUTO_INCREMENT,
  aprobacion_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  celular_contacto varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  cliente_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  cod_cliente varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  cod_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  contacto_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  correo_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  descripcion_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  estado_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  fechaaprobacion varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  fechasolicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  observaciones_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  servicio_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  telefono_solicitud varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  archivo_adjunto tinyblob,
  direccion_solicitud tinytext COLLATE utf8mb4_spanish2_ci,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish2_ci;
