CREATE TABLE cliente (
  create_at date NOT NULL,
  id bigint NOT NULL AUTO_INCREMENT,
  abreviatura varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  actividad_economica varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  apellido varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  cargo_cobro varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  cargo_servicio varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  celular_cobro varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  celular_jefe varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  celular_servicio varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  cod_cliente varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  correo_cobro varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  correo_electronico varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  correo_servicio varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  direccion varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  dv varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  email varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  nombre varchar(255) COLLATE utf8mb4_spanish2_ci NOT NULL,
  nombre_cobro varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  nombre_comercial varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  nombre_contacto varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  razon_social varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  ruc varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  telefono_cobro varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  telefono_empresa varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  telefono_jefe varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  telefono_servicio varchar(255) COLLATE utf8mb4_spanish2_ci DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY UK_cmxo70m08n43599l3h0h07cc6 (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish2_ci;
